# This is a basic workflow to help you get started with Actions

name: TST-CRYPTO UI Tests
env:
  AUTOTEST_EMAIL_PASS: ${{ secrets.AUTOTEST_EMAIL_PASS }}
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron:  '0 7 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: 'BrowserStack Env Setup'
          uses: 'browserstack/github-actions/setup-env@master'
          with:
            ref: crypto
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Check out the repository
          uses: actions/checkout@v3

        - name: Run a test on tst env
          run: mvn test -P suite -Dzone=tst-crypto -Dlocalrun=false -Dgroups=onboarding
